// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMxHS7k0jXd44x2KV3Jqjy1TmXIlgCNE',
    appId: '1:210728402377:web:88440bfaedd87d18bffc18',
    messagingSenderId: '210728402377',
    projectId: 'ecom-8c4f4',
    authDomain: 'ecom-8c4f4.firebaseapp.com',
    storageBucket: 'ecom-8c4f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMwDBmb8eyEG1Y8H6cu-CcFhkzoo4rb4c',
    appId: '1:210728402377:android:089426924d251e72bffc18',
    messagingSenderId: '210728402377',
    projectId: 'ecom-8c4f4',
    storageBucket: 'ecom-8c4f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfU-C3a35dfRKYdIiu6wCf4Yny8ZLwyrQ',
    appId: '1:210728402377:ios:185b8c9d370136cebffc18',
    messagingSenderId: '210728402377',
    projectId: 'ecom-8c4f4',
    storageBucket: 'ecom-8c4f4.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfU-C3a35dfRKYdIiu6wCf4Yny8ZLwyrQ',
    appId: '1:210728402377:ios:185b8c9d370136cebffc18',
    messagingSenderId: '210728402377',
    projectId: 'ecom-8c4f4',
    storageBucket: 'ecom-8c4f4.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSMxHS7k0jXd44x2KV3Jqjy1TmXIlgCNE',
    appId: '1:210728402377:web:b28478d73aa2b380bffc18',
    messagingSenderId: '210728402377',
    projectId: 'ecom-8c4f4',
    authDomain: 'ecom-8c4f4.firebaseapp.com',
    storageBucket: 'ecom-8c4f4.appspot.com',
  );
}
